### ISSUE TITLE
boskos resource runs out

### ISSUE THREAD

**Issue by steuhs** [knative/test-infra#875] opened 2019-06-06 20:47 UTC
In the afternoon of June 5th, multiple integrations tests in across several knative repos failed in a row. (Example failure: https://gubernator.knative.dev/build/knative-prow/pr-logs/pull/knative_serving/4156/pull-knative-serving-upgrade-tests/1136392221466038272/)

The problem recovers later that day (after 17:47pm, see https://prow.knative.dev/?job=*-integration-tests for details)

I have updated the boskos images, in https://github.com/knative/test-infra/pull/872. Though the issue is gone for now, we want to expand the pool to prevent future issues.

**Comment by chaodaiG** [comment] 2019-06-06 21:42
The underlying cause for Boskos running out of resource is not clear yet, so it's not quite convincing that expanding Boskos pool is the proper fix for this issue. Switching to investigating the root cause first

**Comment by steuhs** [comment] 2019-06-07 01:09
@chaodaiG you can feel free to change the title here

**Comment by chaodaiG** [comment] 2019-06-07 14:48
@steuhs , I think the title is fine, will keep it this way

**Comment by chaodaiG** [comment] 2019-06-07 21:33
Parsed all Prow jobs in past 2 days, all Boskos projects were equally used, means Boskos resources were properly cleaned up on all projects, and there is no issue of cleaning up blocked by bad resources. 

Followed 1 Boskos project after it ran e2e tests in test-infra repo, Janitor took ~40 minutes cleaning it up. Since we only had 6 Janitor for 40 Boskos projects, cleaning up queue could be badly backed up during peak hours, increased Janitor to 12 in this PR: https://github.com/knative/test-infra/pull/886

**Comment by chaodaiG** [comment] 2019-06-12 05:48
I think increasing Janitor count worked

/close

**Closed by chaodaiG** 2019-06-12 05:48 UTC
