### ISSUE TITLE
Surface failing test messages in gubernator overview

### ISSUE THREAD

**Issue by srinivashegde86** [knative/test-infra#404] opened 2019-01-18 18:42 UTC
We sometimes fail to showcase the test failures in the gubernator overview and need to go over the entire build-log to check where are the failures. - https://gubernator.knative.dev/build/knative-prow/logs/ci-knative-serving-continuous/1085688690312744960#githubcomknativeservingteste2e-testscaleto50.

This was fixed in #123. But, we shifted to using the new OSS parser from our bash version, and maybe we need to wire it to gubernator?

**Comment by adrcunha** [comment] 2019-01-18 19:03
The parser didn't capture the error message. The message field in the XML is empty. I could swear it used to do that... It's not only for E2E tests: https://gubernator.knative.dev/build/knative-prow/logs/ci-knative-serving-continuous/1083906947670872064

**Comment by adrcunha** [comment] 2019-01-18 19:14
Reproduce with:

```
$ echo -e "=== RUN   TestPasses\n--- PASS: TestPasses (0.01s)\n=== RUN   TestFails\n--- FAIL: TestFails (0.02s)\n    mytest.go:1: Wanted 1. Got 0." | go-junit-report
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
	<testsuite tests="2" failures="1" time="0.030" name="">
		<properties>
			<property name="go.version" value="go1.11"></property>
		</properties>
		<testcase classname="" name="TestPasses" time="0.010"></testcase>
		<testcase classname="" name="TestFails" time="0.020">
			<failure message="Failed" type=""></failure>
		</testcase>
	</testsuite>
</testsuites>
```

**Comment by adrcunha** [comment] 2019-01-18 19:17
The tool was updated recently to include the test output. I used the latest version and it worked as expected:

```
$ echo -e "=== RUN   TestPasses\n--- PASS: TestPasses (0.01s)\n=== RUN   TestFails\n--- FAIL: TestFails (0.02s)\n    mytest.go:1: Wanted 1. Got 0." | go-junit-report
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
	<testsuite tests="2" failures="1" time="0.030" name="">
		<properties>
			<property name="go.version" value="go1.11.2"></property>
		</properties>
		<testcase classname="" name="TestPasses" time="0.010"></testcase>
		<testcase classname="" name="TestFails" time="0.020">
			<failure message="Failed" type="">mytest.go:1: Wanted 1. Got 0.</failure>
		</testcase>
	</testsuite>
</testsuites>
```

**Comment by adrcunha** [comment] 2019-01-18 19:19
It seems to be a simple case of `prow-tests` being outdated (which is weird, as it was last built earlier this month).

**Comment by adrcunha** [comment] 2019-01-18 19:22
According to the history, the test output PR was merged 2 days after `prow-tests` was last built.

**Comment by adrcunha** [comment] 2019-01-19 03:52
Gubernator is now showing the errors again in the summary:

https://gubernator.knative.dev/build/knative-prow/pr-logs/pull/knative_serving/2884/pull-knative-serving-unit-tests/1086469709974474752/

**Closed by adrcunha** 2019-01-19 03:52 UTC
