### ISSUE TITLE
Need monitoring/alerting to check whether Knative prow jobs run properly

### ISSUE THREAD

**Issue by jessiezcc** [knative/test-infra#15] opened 2018-07-18 22:49 UTC
/area test-and-release
/kind dev

Expected Behavior
When Prow job fails to run properly, we should get alert/notification automatically

Actual Behavior
We are finding out the failing job run manually.

**Comment by adrcunha** [comment] 2018-09-05 17:31
I suggest using Stackdriver, at least as an initial solution; this way we can have some monitoring up and running ASAP.

**Comment by steuhs** [comment] 2018-09-22 00:32
It looks like prow has some of its own way of reporting https://github.com/kubernetes/test-infra/tree/master/prow/report
I am trying to see if we can build on top of what they have

**Comment by steuhs** [comment] 2018-10-01 17:45
Yutong is working on prow's reporting feature. https://github.com/kubernetes/test-infra/tree/master/prow/report. I am trying to see if and to what extent we can use that feature

**Comment by steuhs** [comment] 2018-10-01 18:00
Looks like this pkg have a template and function to post prowjob issues on github https://github.com/kubernetes/test-infra/blob/master/prow/report/report.go

**Comment by cjwagner** [comment] 2018-10-01 18:31
> @jessiezcc I chatted with Sen, there is no dashboard that does what I asked above

What exactly are you referring to? I think we have mechanisms to achieve everything listed on this issue except for reporting job failures to slack.

**Comment by steuhs** [comment] 2018-10-01 18:36
@cjwagner I think you are talking about the status context that is showing up at the end of each PR page. Isn't that limited to pre-submit checks? There is also post-submit and periodical jobs we want to monitor, I believe.

**Comment by cjwagner** [comment] 2018-10-01 18:39
That is just one of the mechanisms we have. We have configurable email alerting available through testgrid and we can display the status of the last run of a job with svg badges.

What exactly are you trying to report on?

**Comment by cjwagner** [comment] 2018-12-14 22:44
Those are Testgrid feature so @michelle192837 is the one who implemented them. Please refer to the documentation first though, it describes the features and how to use them: https://github.com/kubernetes/test-infra/tree/master/testgrid#email-alerts

**Comment by adrcunha** [comment] 2018-12-14 22:47
Testgrid e-mail alerting is already enabled by #261. We want a lower level job monitoring so we can act faster when something goes wrong.

**Comment by cjwagner** [comment] 2018-12-14 23:09
According to that PR body, you configured Testgrid to report only after 3 consecutive failures. If you reported on the first failure that would have the effect you want right? Or are you saying that Testgrid's update period itself is too slow for some use case that you have?

**Comment by adrcunha** [comment] 2018-12-14 23:18
> Or are you saying that Testgrid's update period itself is too slow for some use case that you have?

That's correct. Example: suppose that we push a bad Prow config, for example, and the crons or pull jobs don't run. Currently we have no way of knowing that, unless someone stumbles upon it and reports (e.g., pull test jobs never finish for your PR).

**Comment by adrcunha** [comment] 2018-12-19 05:48
Maybe that was just a bad example. But the idea, as Cold put it clearly, is to have some sort of monitoring in place so we are aware of issues with our Prow jobs (presubmits, postsubmits, crons, etc) way faster than the time it takes for Testgrid to update and us to check it out and realize that something is not right.

That's the motivation. I'll leave the details to Stephen, who's working on this issue.

**Comment by steuhs** [comment] 2019-01-08 23:44
@adrcunha I read this https://github.com/kubernetes/test-infra/tree/master/testgrid#email-alerts. It seems to me that we can use the TestGrid, with num_failures_to_alert set to 1. With that change, I don't see any use case where TestGrid would be too slow - we don't need to rely on periodical jobs, we can monitor on post-submit jobs to get the failure report as soon as it happens. Please correct me if you can give me a use case that we cannot use TestGrid's alerting mechanism. @michelle192837 Please provide your opinion as well.

**Comment by adrcunha** [comment] 2019-01-08 23:53
`num_failures_to_alert` will only report failed tests, not broken jobs (one that never reports test status, for example). Also, it has a delay of up to 2h due to Testgrid updates. This issue is about monitoring the jobs, not test failures.

**Comment by michelle192837** [comment] 2019-01-08 23:59
Adriano is correct that you'll have to deal with the TestGrid update delay either way (though it's a lot less than 2H in worst case in external; more like 30 minutes delay with bad luck). That said, it does seem like broken jobs should timeout and report at some point, producing a failed result, so that the only delay you have to deal with is the update delay.

So I guess if the problem is 'I want to know when my Prow jobs are failing', you can get that (holding to TestGrid's update cycles) with TestGrid alerting. If it's a potential misconfiguration thing for Prow, that seems like that should be added to/handled by Prow presubmit tests? And if Prow jobs are staying up forever, seems like that should be fixed with a timeout.

**Comment by adrcunha** [comment] 2019-01-09 00:11
Timeouts are already in place, `num_failures_to_alert` is already setup (but won't work until we have our own Testgrid backend). On top of that, we want the quickest possible way to identify when Prow jobs are misbehaving; we don't want to wait 30 minutes, or 2h, or for a user to report issues on Slack. Scenarios include bad configs (secrets, ACLs), k8s pods failures, resource exhaustion, etc. Less frequent jobs (like the nightly releases or playground update) are more concerning, since we tend to realize they're broken too late in the game when we rely only on Testgrid (even if the report is automated).

**Comment by steuhs** [comment] 2019-01-16 01:13
@adrcunha I discussed with @cjwagner, bad configs such as invalid container address and wrong secrets will result in pending state and there is no way to tell if there is any real issue (see https://github.com/kubernetes/test-infra/issues/9694) when it is in pending state. We can not alter that unless we change the design and coding of Kubernetes itself. To avoid long wait time we can shorten the timeout for pending state to 20 mins or so - we can tailor the number by looking into historical duration of pending state. 
Cole also mentioned prow rarely fail before a job start - it only happens several times in a year, for different reasons. 
For the particular case of checking whether the knative docker images are missing or non-accessible, there is an internal task assigned to @tcnghia  
Considering all the three factors mentioned above, I think the most cost effective way is to shorten the timeout for pending state and monitor on prow job status change.

**Comment by steuhs** [comment] 2019-01-16 21:50
@adrcunha 
2. & 4. We don't necessarily need to rule out Stackdriver because the status change can be monitored through there. Indeed it seems to be a better alternative to monitor the status change there, comparing to using Crier. I am doing the investigation. One potential advantage of using Stackdriver would be the alerting system it provides 
3. I mean Nghia is working on "Cloud Run GKE prober should fail when release images are missing" (b/120081643). So for those kinds of failures we will have a separate solution

**Comment by adrcunha** [comment] 2019-01-16 21:58
3 doesn't apply.
For 4 looks like I wasn't clear. I indeed meant "do NOT rule out Stackdriver unless it's proven that it doesn't help". I advocated using SD as an easy monitoring solution from day 1.

**Comment by srinivashegde86** [comment] 2019-05-20 18:09
Should be handled by the knative-monitoring proposal

**Closed by srinivashegde86** 2019-05-20 18:09 UTC
