### ISSUE TITLE
Don't publish partial releases on failures

### ISSUE THREAD

**Issue by ericKlawitter** [knative/test-infra#714] opened 2019-04-25 20:49 UTC
There is an issue in our release script in which partial releases can be published. When an issue occurs during the release script, we should fail without publishing an incomplete release. 

This happened with [serving release 0.5.2](https://github.com/knative/serving/releases/tag/v0.5.2), when a [502 caused](https://gubernator.knative.dev/build/knative-prow/logs/ci-knative-serving-dot-release/1120613746985668608) the release script to fail, but the release was published with only  partial asset files. We should fix this behavior going forward.

**Comment by adrcunha** [comment] 2019-07-14 01:29
Nikhil left the team, assigning this issue to me.
/assign adrcunha
/unassign nbarthwal

**Comment by adrcunha** [comment] 2019-07-16 18:43
This is caused by the hub tool. Release assets are uploaded here:

https://github.com/github/hub/blob/01429de9a214d37fc76db7ccc9bc3af78d56a1fc/github/client.go#L387

If an error happens, the function bubbles up the error. Then in

https://github.com/github/hub/blob/ad6e36233d8515be97ea697e2c54451b8e674958/commands/release.go#L630

it will simply abort the process, causing a partial release to be published:

https://github.com/github/hub/blob/ad6e36233d8515be97ea697e2c54451b8e674958/utils/utils.go#L18

**Comment by adrcunha** [comment] 2019-07-16 19:08
Filed an issue for the hub tool (https://github.com/github/hub/issues/2197), thus closing this one.

/close

**Closed by adrcunha** 2019-07-16 19:08 UTC
Labels: kind/enhancement
