### ISSUE TITLE
Coverage tabs in TestGrid are all red despite the good numbers

### ISSUE THREAD

**Issue by adrcunha** [knative/test-infra#919] opened 2019-06-13 15:41 UTC
Despite high coverage numbers, all entries in code coverage tabs are marked red.

![image](https://user-images.githubusercontent.com/35786489/59446723-e3fbb900-8db6-11e9-9386-0f9b5a5fa279.png)

Looks like the issue started on 6/3.

/assign @coryrc 
/cc @steuhs @srinivashegde86

**Comment by adrcunha** [comment] 2019-06-13 15:42
It seems to be related to entries get a . prefix, eg:

![image](https://user-images.githubusercontent.com/35786489/59446861-2624fa80-8db7-11e9-9ef1-c5a88ae1dd0b.png)

**Comment by adrcunha** [comment] 2019-06-13 15:45
Looks like 852 is the culprit (it was merged on 6/3), see https://github.com/knative/test-infra/pull/852/files#r293448726

/assign @Fredy-Z

**Comment by adrcunha** [comment] 2019-06-13 18:29
Synced up with Chi, and he mentioned that the image he built/pushed after 852 contained previous changes that were not published before. The JUnit XML files before and after 6/3 are different:

https://storage.googleapis.com/knative-prow/logs/ci-knative-build-go-coverage/1135350603736682497/artifacts/junit_bazel.xml
https://storage.googleapis.com/knative-prow/logs/ci-knative-build-go-coverage/1135712993296781312/artifacts/junit_bazel.xml

https://github.com/knative/test-infra/pull/726 used the shared JUnit XML generator in the code coverage tool. The new XML contains `<failure>true</failure>`, and TestGrid not being able do understanding it would explain all the redness. The . prefix doesn't appear in the XML, but could be explained by the package name (852 above) and how TestGrid processed the XML.

**Comment by adrcunha** [comment] 2019-06-13 18:38
Code coverage image was generated on 2/16. All PRs from 2/16 until now are potential cuprits. :(

**Comment by Fredy-Z** [comment] 2019-06-13 18:49
I don't see #852 would cause this error. Reassigning for further investigation.
/unassign @coryrc 
/assign @steuhs @srinivashegde86

**Comment by steuhs** [comment] 2019-06-17 21:39
I think this is the cause: <failure>false</failure> was treated like a <failure>
We should either
1. undo #726
2. change how testgrid treats <failure>false</failure>

**Comment by adrcunha** [comment] 2019-06-17 22:11
1 is bad because you're back to duplicate, custom code.
2 is unnecessary complexity, unless it's a bug in TestGrid.

First thing to do is to make sure this is indeed the root cause.

**Comment by srinivashegde86** [comment] 2019-06-17 22:53
If that is the issue, can we just add the tag only on failures? Seems better than having duplicate code.

**Comment by steuhs** [comment] 2019-06-17 22:58
> If that is the issue, can we just add the tag only on failures? Seems better than having duplicate code.

I believe my original implementation was to only add tag on failures. 
I'll see double check if that is the root cause

**Comment by steuhs** [comment] 2019-06-17 23:19
> 1 is bad because you're back to duplicate, custom code.
> 2 is unnecessary complexity, unless it's a bug in TestGrid.
> 
> First thing to do is to make sure this is indeed the root cause.

It was the root cause. I verified by manually removing that tag from the some entries and it turned the corresponding cell green. See https://testgrid.knative.dev/serving#coverage

**Closed** 2019-06-18 21:34 UTC
