### ISSUE TITLE
All *.knative.dev sites are not reachable.

### ISSUE THREAD

**Issue by dushyanthsc** [knative/test-infra#538] opened 2019-02-28 22:18 UTC
https://prow.knative.dev/ is not reachable at this time. We are seeing a "Error: Server Error" on the landing page.

**Comment by srinivashegde86** [comment] 2019-02-28 22:19
all *.knative.dev sites are down including gubernator and testgrid

**Comment by dushyanthsc** [comment] 2019-02-28 22:20
Updated the issue.

**Comment by srinivashegde86** [comment] 2019-02-28 22:29
Open registration has now begun for .dev domains. Maybe related?

**Comment by adrcunha** [comment] 2019-02-28 23:20
Root cause was accidental project deletion. It's now undeleted, things are back to normal.

Reassigning to @steuhs for a proper post-mortem on this.

/assign @steuhs

**Comment by steuhs** [comment] 2019-04-02 01:35
Post Mortem completed and reviewed
https://docs.google.com/document/d/1yiFiEqcxOMgAz8aETApIDzKvR7NfIZ1GfYNY1jMDxW0/

**Closed** 2019-04-02 01:36 UTC
